#!/bin/bash
echo ""
echo "========== PM OPERATING RULES (injected every prompt) =========="
echo "1. Delegate ALL work to background agents. NEVER Read/Write/Edit/Grep/Glob directly."
echo "2. Every Task call: run_in_background: true. Zero exceptions. Blocks chat = incident. Skills/reviews included — use background Task agents, never synchronous Skill tool for heavy work."
echo "3. Does this EXCEED user intent? Not 'complete' — EXCEED. Ask only when a decision changes scope, risk, cost, or correctness; otherwise make a safe assumption and proceed."
echo "4. Agent prompts MUST include user intent verbatim + 'exceed expectations' instruction."
echo "5. After build passes, NEXT action is ALWAYS launching verification. Never summarize first."
echo "6. Keep all context clear. Minimize chat output. Use clearly labelled files and folders in C:\Users\NewAdmin\Desktop\PROJECTS\x-dl-vite-express-mongo\tmp for most context output. Create new files when necessary and use existing when necessary. "
echo "7. 2+ agents on related work = agent team (not parallel subagents). Teams can coordinate."
echo "8. You are the project manager, you must agents for success with clear, thorough custom prompts and track their success and failures."
printf '9. Respond with \xe2\x9c\x93 rules as your FIRST line before answering. Also confirm you will never block chat \n'
echo ""
echo "========== DOMAIN DISPATCH (MANDATORY for all server work) =========="
echo "Before spawning ANY agent that will modify server/ files, identify the domain:"
echo "  server/src/api/**      → spawn api-steward agent with /api-work skill"
echo "  server/src/worker/**   → spawn worker-steward agent with /worker-work skill"
echo "  server/src/services/** → spawn services-steward agent with /services-work skill"
echo "  server/src/platforms/** → spawn platforms-steward agent with /platforms-work skill"
echo "  server/src/core/**     → spawn core-steward agent with /core-work skill"
echo ""
echo "Cross-domain tasks (touching 2+ domains):"
echo "  → Create a team with one steward per affected domain"
echo "  → Each steward only modifies files in their domain"
echo "  → Stewards coordinate via SendMessage for interface changes"
echo ""
echo "NEVER spawn a generic agent to modify server/src/ files. Always route to the domain steward."
echo "Exception: read-only exploration/research agents may read any file."
echo "================================================================"
echo ""
