const ERROR_CODES = Object.freeze({
  INVALID_TWEET_URL: 'INVALID_TWEET_URL',
  DB_NOT_CONNECTED: 'DB_NOT_CONNECTED',
  INVALID_JOB_ID: 'INVALID_JOB_ID',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  LIST_JOBS_FAILED: 'LIST_JOBS_FAILED',
  LOAD_JOB_FAILED: 'LOAD_JOB_FAILED',
  CREATE_JOB_FAILED: 'CREATE_JOB_FAILED',
  UPDATE_STATUS_FAILED: 'UPDATE_STATUS_FAILED',
});

module.exports = {
  ERROR_CODES,
};
